Controllers/CityController.cs
using AdvanceAjaxCRUD.Data;
using AdvanceAjaxCRUD.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AdvanceAjaxCRUD.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class CityController : Controller
    {

        private readonly AppDbContext _context;

        public CityController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<City> Cities;
            Cities = _context.Cities.Include(c => c.Country).ToList();
            return View(Cities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            City City = new City();
            ViewBag.Countries = GetCountries();
            return View(City);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(City City)
        {

            _context.Add(City);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            City City = _context.Cities
               .Include(c => c.Country)
            .FirstOrDefault(c => c.Id == Id);

            return View(City);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            City City = _context.Cities
              .Where(c => c.Id == Id).FirstOrDefault();

            ViewBag.Countries = GetCountries();

            return View(City);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(City City)
        {
            _context.Attach(City);
            _context.Entry(City).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Delete(int Id)
        {
            City City = _context.Cities
              .Where(c => c.Id == Id).FirstOrDefault();

            return View(City);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(City City)
        {
            _context.Attach(City);
            _context.Entry(City).State = EntityState.Deleted;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        private List<SelectListItem> GetCountries()
        {
            var lstCountries = new List<SelectListItem>();

            List<Country> Countries = _context.Countries.ToList();

            lstCountries = Countries.Select(ct => new SelectListItem()
            {
                Value = ct.Id.ToString(),
                Text = ct.Name
            }).ToList();

            var defItem = new SelectListItem()
            {
                Value = "",
                Text = "----Select Country----"
            };

            lstCountries.Insert(0, defItem);

            return lstCountries;
        }
        [HttpGet]
        public IActionResult CreateModalForm(int countryId)
        {
            City city = new City();
            city.CountryId = countryId;
            city.CountryName = GetCountryName(countryId);
            return PartialView("_CreateModalForm", city);
        }
        [HttpPost]
        public IActionResult CreateModalForm(City city)
        {
            _context.Add(city);
            _context.SaveChanges();
            return NoContent();
        }
        private string GetCountryName(int countryId)
        {
            if (countryId == 0) return "";
            string CountryName = _context.Countries.Where(ct => ct.Id == countryId)
                                    .Select(ct => ct.Name).Single().ToString();
            return CountryName;
            
        }

    }
}

Controllers/CountryController.cs
using AdvanceAjaxCRUD.Data;
using AdvanceAjaxCRUD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Metrics;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace AdvanceAjaxCRUD.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {

        private readonly AppDbContext _context;

        public CountryController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 2)
        {
            List<Country> countries;
            countries = _context.Countries.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
            var totalCount = _context.Countries.Count();

            ViewBag.TotalCount = totalCount;
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;
            //if (TempData["SuccessMessage"] != null)
            //{
            //    ViewBag.SuccessMessage = TempData["SuccessMessage"];
            //}
            return View(countries);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Country country = new Country();
            return View(country);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(Country country)
        {
            _context.Add(country);
            _context.SaveChanges();
            TempData["SuccessMessage"] = "Country has been created successfully.";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult CreateModalForm()
        {
            Country country = new Country();
            return PartialView("_CreateModalForm", country);
        }
        [HttpPost]
        public IActionResult CreateModalForm(Country country)
        {
            _context.Add(country);

            _context.SaveChanges();
            return NoContent();
        }
        [HttpGet]
        public IActionResult Details(int Id)
        {
            Country country = GetCountry(Id);
            return View(country);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Country country = GetCountry(Id);
            return View(country);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Country country)
        {
            _context.Attach(country);
            _context.Entry(country).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private Country GetCountry(int id)
        {
            Country country;
            country = _context.Countries
             .Where(c => c.Id == id).FirstOrDefault();
            return country;

        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Country country = GetCountry(Id);
            return View(country);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(Country country)
        {

            try
            {
                _context.Attach(country);
                _context.Entry(country).State = EntityState.Deleted;
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                _context.Entry(country).Reload();
                ModelState.AddModelError("", ex.InnerException.Message);
                return View(country);
            }
            return RedirectToAction(nameof(Index));
        }

        public JsonResult GetCountries()
        {
            var lstCountries = new List<SelectListItem>();

            List<Country> Countries = _context.Countries.ToList();

            lstCountries = Countries.Select(ct => new SelectListItem()
            {
                Value = ct.Id.ToString(),
                Text = ct.Name
            }).ToList();

            var defItem = new SelectListItem()
            {
                Value = "",
                Text = "----Select Country----"
            };

            lstCountries.Insert(0, defItem);

            return Json(lstCountries);
        }

    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdvanceAjaxCRUD.Data;
using AdvanceAjaxCRUD.Models;
using iTextSharp.text.pdf;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using AdvanceAjaxCRUD.Helper;

namespace AdvanceAjaxCRUD.Controllers
{
    public class PostsController : Controller
    {
        private readonly AppDbContext _context;

        public PostsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Post.ToListAsync());
        }




        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Post == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Post == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Post == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Post == null)
            {
                return Problem("Entity set 'AppDbContext.Post'  is null.");
            }
            var post = await _context.Post.FindAsync(id);
            if (post != null)
            {
                _context.Post.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Post.Any(e => e.Id == id);
        }
        public  FileResult GeneratePDF(int id)
        {
            // Retrieve dynamic content from the database
            string recipientName = "Md Sohanur Rahaman"; // dynamic Name of the Recipent
            string meetingNo = "1330"; // dynamic meeting no
            string date = "05 May, 2023"; // Date
            string venue = "Board Room , Head Office, Motijheel"; // Venue
            string address = "Dynamic Address"; // Address
            string startTime = "2:00 PM"; // Start Time
                                          //string logoUrl = ... // URL of the company logo
            string companyAddress = "Dilkusha Cprporate Area,Motijheel,Dhaka"; // Company Address
            string senderName = "Company Secretary"; // Name of the sender
            string jobPosition = "General Manager"; // Job Position
            string companyName = "Pubali Bank Limited"; // Company Name

            var post =  _context.Post.FirstOrDefault(m => m.Id == id);

            // Create a string variable to hold the invitation letter template with placeholders for the dynamic content
            string template = @"
            <p>[Date]</p>
            <p>[Company Addresss]</p>
    
            <p>[dynamic Name of the Recipent]</p>
            <p>Name of the Company</p>
            <p>Address</p>
            <br/>
            <p>Subject: To Attend in the meeting [dynamic meeting no].</p>

            <p>Dear Sir,</p>
             <br/>
            <p>It is with great pleasure that I invite you to the company’s meeting [dynamic meeting no] board meeting. The event shall be held on [Date] at [Venue] located in [Address] from [Start Time].</p>

            <p>As one of the most important people in the company, it would be such an honor if you could grace our Event with your presence. It is also an opportunity for us to thank you for all your contributions to the success of the company for the past years.</p>
            <br/>
            <p>I am looking forward to your presence at the business convention.</p>
             <br/>
             <p>[Post]</p>
            <p>Yours faithfully,</p>

            <p>Name and Signature<br>Job Position<br>Company Name</p>";

            // Replace placeholders in the template with actual values
            template = template.Replace("[dynamic Name of the Recipent]", recipientName)
                               .Replace("[dynamic meeting no]", meetingNo)
                               .Replace("[Date]", date)
                               .Replace("[Venue]", venue)
                               .Replace("[Address]", address)
                               .Replace("[Start Time]", startTime)
                               //.Replace("[LOGO]", "<img src='" + logoUrl + "' alt='Company Logo' />")
                               .Replace("[Company Addresss]", companyAddress)
                               .Replace("Name and Signature", senderName)
                               .Replace("Job Position", jobPosition)
                               .Replace("Company Name", companyName)
                               .Replace("[Post]", post.Content);
            // Create a new Document object
            Document document = new Document(PageSize.A4, 50, 50, 25, 25);

            // Create a new PdfWriter that will write to a MemoryStream
            MemoryStream stream = new MemoryStream();
            PdfWriter writer = PdfWriter.GetInstance(document, stream);


            // Set the custom page event helper
            writer.PageEvent = new CustomPdfPageEventHelper();

            // Open the Document
            document.Open();
            // Load the image from the file path
            var logo = Image.GetInstance(@"C:\Users\sohan\Downloads\logo.jpg");

            // Resize the image to fit within the page
            logo.ScaleToFit(150f, 150f);

            // Set the image alignment to the right
            logo.Alignment = Element.ALIGN_RIGHT;

            // Add the image to the Document
            document.Add(logo);

            // Parse the HTML template and add it to the Document
            using (TextReader reader = new StringReader(template))
            {
                HTMLWorker worker = new HTMLWorker(document);
                worker.Parse(reader);
            }

            // Close the Document
            document.Close();

            // Convert the MemoryStream to a byte array
            byte[] fileContents = stream.ToArray();

            // Return the PDF as a FileResult
            string fileName = "invitation_letter.pdf";
            return File(fileContents, "application/pdf", fileName);
        }
       

    }
}

Views/Shared/_CreateModalDialog.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="DivCreateDialogHolder" class="modal fade text-width:30%;" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="DivCreateDialog" class="modal-body">
               
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
                <div class="btn-group">
                    <div>
                        <button id="dupBackbtn" type="button" class="btn btn-danger" data-icon="back"
                        data-bs-dismiss="modal">Back</button>
                    </div>
                    <div class="ml-4">
                        <input id="dupSubmitBtn" type="button" value="Save" class="btn btn-primary" onclick="SubmitModalForm()" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor _httpHttpContextAccessor;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdvanceAjaxCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdvanceAjaxCRUD.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdvanceAjaxCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                        @if(_httpHttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">@_httpHttpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "FirstName").Value</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller ="Account" asp-action="SignOut" method="post">
                                    @Html.AntiForgeryToken()
                                    <button type="submit">Sign Out</button>
                                </form>
                             
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_CreateModalDialog" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AdvanceAjaxCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>